
title: "Trabajos Prácticos IE"
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "pasos_R/*.qmd"

website:
  title: "Trabajo Práctico IE"

  sidebar:
    style: docked
    search: true

    contents:
      - href: index.qmd
        text: Inicio

      - section: "TRABAJO PRÁCTICO 2"
        contents:
          - href: tp2/index.qmd
            text: Presentación
          - href: tp2/ejercicio2.1.qmd
            text: Ejercicio 2.1
          - href: tp2/ejercicio2.2.qmd
            text: Ejercicio 2.2
          - href: tp2/ejercicio2.3.qmd
            text: Ejercicio 2.3
          - href: tp2/ejercicio2.4.qmd
            text: Ejercicio 2.4
          - href: tp2/ejercicio2.5.qmd
            text: Ejercicio 2.5
          - href: tp2/ejercicio2.6.qmd
            text: Ejercicio 2.6
          - href: tp2/ejercicio2.7.qmd
            text: Ejercicio 2.7

      - section: "TRABAJO PRÁCTICO 3"
        contents:
          - href: tp3/index.qmd
            text: Presentación
          - href: tp3/ejercicio3.1.qmd
            text: Ejercicio 3.1
          - href: tp3/ejercicio3.2.qmd
            text: Ejercicio 3.2
          - href: tp3/ejercicio3.3.qmd
            text: Ejercicio 3.3
          - href: tp3/ejercicio3.4.qmd
            text: Ejercicio 3.4
          - href: tp3/ejercicio3.5.qmd
            text: Ejercicio 3.5
          - href: tp3/ejercicio3.6.qmd
            text: Ejercicio 3.6
          - href: tp3/ejercicio3.7.qmd
            text: Ejercicio 3.7
          - href: tp3/ejercicio3.8.qmd
            text: Ejercicio 3.8
          - href: tp3/ejercicio3.9.qmd
            text: Ejercicio 3.9
            
      - section: "TRABAJO PRÁCTICO 4"
        contents:
          - href: tp4/index.qmd
            text: Presentación
          - href: tp4/ejercicio4.1.qmd
            text: Ejercicio 4.1
          - href: tp4/ejercicio4.2.qmd
            text: Ejercicio 4.2
          - href: tp4/ejercicio4.3.qmd
            text: Ejercicio 4.3
            
      - section: "TRABAJO PRÁCTICO 5"
        contents:
          - href: tp5/index.qmd
            text: Presentación
          - href: tp5/ejercicio5.1.qmd
            text: Ejercicio 5.1
          - href: tp5/ejercicio5.2.qmd
            text: Ejercicio 5.2
          - href: tp5/ejercicio5.3.qmd
            text: Ejercicio 5.3
          - href: tp5/ejercicio5.4.qmd
            text: Ejercicio 5.4
          - href: tp5/ejercicio5.5.qmd
            text: Ejercicio 5.5
          - href: tp5/ejercicio5.6.qmd
            text: Ejercicio 5.6


      - section: "TRABAJO PRÁCTICO 7"
        contents:
          - href: tp7/ejercicio1.qmd
            text: Ejercicio 7.1

      - section: "TRABAJO PRÁCTICO 8"
        contents:
          - href: tp8/ejercicio1.qmd
            text: Ejercicio 8.1

      - section: "TRABAJO PRÁCTICO 9"
        contents:
          - href: tp9/ejercicio1.qmd
            text: Ejercicio 9.1

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css


