---
title: "Ejercicio 4.3_R_1"
---

# 1. Configurar los parámetros del experimento

```{r}
set.seed(123) # Asegura que los resultados sean replicables 
replicas<- 100 # Número de repeticiones (réplicas) 
pi <- 0.80 # Probabilidad de éxito de la marca Z
```


 

# 2. Definir los tamaños de muestra a evaluar

```{r}
tamanos_n <- c(20, 30, 50)
```



# Configurar la pantalla para ver los 3 gráficos juntos (1 fila, 3 columnas)

```{r}
par(mfrow = c(1, 3))

```

# 3. Bucle para simular, calcular p y graficar para cada n

```{r}
for (n in tamanos_n) {

# Simular 100 muestras binomiales de tamaño n 
# rbinom genera el número de éxitos 'X' directamente 
exitos_X <- rbinom(n = replicas, size = n, prob = pi)

# Calcular el estadístico p (proporción muestral) para cada réplica
proporciones_p <- exitos_X / n

# Construir el histograma de las proporciones obtenidas
hist(proporciones_p, 
     breaks = seq(0, 1, by = 0.05), # Intervalos de las barras 
     xlim =c(0.4, 1), # Límites del eje X enfocados en los datos 
     main = paste("n =", n), # Título del gráfico 
     xlab = "Proporción muestral (p)", ylab = "Frecuencia", col = "skyblue", border = "white")

# Línea roja para mostrar dónde está el valor real (0.80)
abline(v = pi, col = "red", lwd = 2, lty = 2) 
}

```



