---
title: "Ejercicio 2.3"
---

En un estudio en un monte del Chaco árido se midieron los perímetros basales de troncos de plantas de quebracho blanco (en centímetros) obteniéndose la siguiente información:

Tabla: Perímetros basales de troncos de quebracho blanco (cm)

|     |     |     |     |     |     |     |     |     |     |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| 138 | 164 | 150 | 132 | 144 | 125 | 149 | 157 | 146 | 158 |
| 140 | 147 | 136 | 148 | 152 | 144 | 168 | 128 | 138 | 176 |
| 163 | 121 | 154 | 165 | 146 | 173 | 142 | 147 | 135 | 153 |
| 140 | 135 | 161 | 145 | 135 | 161 | 145 | 142 | 150 | 156 |


1) Identifique:

a) el experimento que se realiza.

b) la unidad experimental.

c) la población de unidades y la población estadística.

d) la variable de estudio y a qué tipo corresponde.

2. Construya la distribución de frecuencias y grafique adecuadamente.

3. Calcule la moda, la mediana y la media aritmética considerando el ítem 2.

4. Construya la distribución de frecuencias y grafique adecuadamente, utlizando el programa estadístico
[Ver pasos para resolver en R](../pasos_R/ejercicio2.3_R_1.html)

5. Calcule las medidas del ítem 3 con los datos puros.
      Utilice el programa R siguiendo la guía disponible aquí:
[Ver pasos para resolver en R](../pasos_R/ejercicio2.3_R_2.html)

6.  ¿Qué puede usted afirmar respecto de los cálculos obtenidos en 3 y 5?  
7. Calcule una medida de variabilidad apropiada para la media aritmética y otra para la mediana obtenidas en los ítems 3 y 5.
Utilice el programa R siguiendo la guía disponible aquí:
[Ver pasos para resolver en R](../pasos_R/ejercicio2.3_R_3.html)

7. Construya el boxplot, en  forma manual y usando el programa estadístico. [Ver pasos para resolver en R](../pasos_R/ejercicio2.3_R_4.html)
  

8. Elabore las conclusiones que crea convenientes a partir de los resultados obtenidos.  